swagger: '2.0'
info:
  title: XSS test for Swagger
  description: |
        <math><annotation-xml encoding=\"text/html\"><p><style><p title=\"</style><svg/onload=alert(1)<!--\"></style>
paths:
  /test:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - test
      operationId: findtest
      summary: Finds all tests
