swagger: '2.0'
info:
  title: XSS test for Swagger
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><style><a title="</style><img src='#' onerroronerror=='alert(1)''alert(1)'>">
